#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const sdkRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(sdkRoot, '..', '..');
const protoPath = path.join(repoRoot, 'holons', 'grace-op', '_protos', 'holons', 'v1', 'observability.proto');
const outPath = path.join(sdkRoot, 'src', 'gen', 'holons', 'v1', 'observability.js');

if (!fs.existsSync(protoPath)) {
    throw new Error(`missing canonical observability proto: ${protoPath}`);
}

const output = `'use strict';

// Code generated by npm run generate:protos. DO NOT EDIT.

const { root } = require('./root');

const LogsRequest = root.lookupType('holons.v1.LogsRequest');
const MetricsRequest = root.lookupType('holons.v1.MetricsRequest');
const EventsRequest = root.lookupType('holons.v1.EventsRequest');
const AnyValue = root.lookupType('holons.v1.AnyValue');
const KeyValue = root.lookupType('holons.v1.KeyValue');
const Resource = root.lookupType('holons.v1.Resource');
const LogRecord = root.lookupType('holons.v1.LogRecord');
const Metric = root.lookupType('holons.v1.Metric');
const Gauge = root.lookupType('holons.v1.Gauge');
const Sum = root.lookupType('holons.v1.Sum');
const Histogram = root.lookupType('holons.v1.Histogram');
const NumberDataPoint = root.lookupType('holons.v1.NumberDataPoint');
const HistogramDataPoint = root.lookupType('holons.v1.HistogramDataPoint');
const SeverityNumber = root.lookupEnum('holons.v1.SeverityNumber').values;
const AggregationTemporality = root.lookupEnum('holons.v1.AggregationTemporality').values;

function makeSerializer(type) {
    return (value) => Buffer.from(type.encode(type.fromObject(value || {})).finish());
}

function makeDeserializer(type) {
    return (buffer) => type.toObject(type.decode(buffer), {
        longs: String,
        enums: Number,
        defaults: true,
        arrays: true,
        objects: true,
        oneofs: true,
    });
}

function method(path, requestType, responseType, responseStream, originalName) {
    return {
        path,
        requestStream: false,
        responseStream,
        requestSerialize: makeSerializer(requestType),
        requestDeserialize: makeDeserializer(requestType),
        responseSerialize: makeSerializer(responseType),
        responseDeserialize: makeDeserializer(responseType),
        originalName,
    };
}

const HOLON_OBSERVABILITY_SERVICE_DEF = {
    Logs: method('/holons.v1.HolonObservability/Logs', LogsRequest, LogRecord, true, 'logs'),
    Metrics: method('/holons.v1.HolonObservability/Metrics', MetricsRequest, Metric, true, 'metrics'),
    Events: method('/holons.v1.HolonObservability/Events', EventsRequest, LogRecord, true, 'events'),
};

module.exports = {
    root,
    LogsRequest,
    MetricsRequest,
    EventsRequest,
    AnyValue,
    KeyValue,
    Resource,
    LogRecord,
    Metric,
    Gauge,
    Sum,
    Histogram,
    NumberDataPoint,
    HistogramDataPoint,
    SeverityNumber,
    AggregationTemporality,
    HOLON_OBSERVABILITY_SERVICE_DEF,
};
`;

fs.writeFileSync(outPath, output);
console.log(`generated ${path.relative(repoRoot, outPath)}`);
