package org.organicprogramming.gudule.greeting.daemon.kotlin

data class GreetingEntry(
    val code: String,
    val name: String,
    val nativeLabel: String,
    val template: String,
)

val greetings: List<GreetingEntry> = listOf(
    GreetingEntry(code = "en", name = "English", nativeLabel = "English", template = "Hello, %s"),
    GreetingEntry(code = "fr", name = "French", nativeLabel = "Français", template = "Bonjour, %s"),
    GreetingEntry(code = "es", name = "Spanish", nativeLabel = "Español", template = "Hola, %s"),
    GreetingEntry(code = "de", name = "German", nativeLabel = "Deutsch", template = "Hallo, %s"),
    GreetingEntry(code = "it", name = "Italian", nativeLabel = "Italiano", template = "Ciao, %s"),
    GreetingEntry(code = "pt", name = "Portuguese", nativeLabel = "Português", template = "Olá, %s"),
    GreetingEntry(code = "nl", name = "Dutch", nativeLabel = "Nederlands", template = "Hallo, %s"),
    GreetingEntry(code = "ru", name = "Russian", nativeLabel = "Русский", template = "Привет, %s"),
    GreetingEntry(code = "ja", name = "Japanese", nativeLabel = "日本語", template = "こんにちは、%sさん"),
    GreetingEntry(code = "zh", name = "Chinese", nativeLabel = "中文", template = "你好，%s"),
    GreetingEntry(code = "ko", name = "Korean", nativeLabel = "한국어", template = "안녕하세요, %s"),
    GreetingEntry(code = "ar", name = "Arabic", nativeLabel = "العربية", template = "مرحبا، %s"),
    GreetingEntry(code = "hi", name = "Hindi", nativeLabel = "हिन्दी", template = "नमस्ते, %s"),
    GreetingEntry(code = "tr", name = "Turkish", nativeLabel = "Türkçe", template = "Merhaba, %s"),
    GreetingEntry(code = "pl", name = "Polish", nativeLabel = "Polski", template = "Cześć, %s"),
    GreetingEntry(code = "sv", name = "Swedish", nativeLabel = "Svenska", template = "Hej, %s"),
    GreetingEntry(code = "no", name = "Norwegian", nativeLabel = "Norsk", template = "Hei, %s"),
    GreetingEntry(code = "da", name = "Danish", nativeLabel = "Dansk", template = "Hej, %s"),
    GreetingEntry(code = "fi", name = "Finnish", nativeLabel = "Suomi", template = "Hei, %s"),
    GreetingEntry(code = "cs", name = "Czech", nativeLabel = "Čeština", template = "Ahoj, %s"),
    GreetingEntry(code = "ro", name = "Romanian", nativeLabel = "Română", template = "Bună, %s"),
    GreetingEntry(code = "hu", name = "Hungarian", nativeLabel = "Magyar", template = "Szia, %s"),
    GreetingEntry(code = "el", name = "Greek", nativeLabel = "Ελληνικά", template = "Γεια σου, %s"),
    GreetingEntry(code = "th", name = "Thai", nativeLabel = "ไทย", template = "สวัสดี, %s"),
    GreetingEntry(code = "vi", name = "Vietnamese", nativeLabel = "Tiếng Việt", template = "Xin chào, %s"),
    GreetingEntry(code = "id", name = "Indonesian", nativeLabel = "Bahasa Indonesia", template = "Halo, %s"),
    GreetingEntry(code = "ms", name = "Malay", nativeLabel = "Bahasa Melayu", template = "Hai, %s"),
    GreetingEntry(code = "sw", name = "Swahili", nativeLabel = "Kiswahili", template = "Habari, %s"),
    GreetingEntry(code = "he", name = "Hebrew", nativeLabel = "עברית", template = "שלום, %s"),
    GreetingEntry(code = "uk", name = "Ukrainian", nativeLabel = "Українська", template = "Привіт, %s"),
    GreetingEntry(code = "bn", name = "Bengali", nativeLabel = "বাংলা", template = "নমস্কার, %s"),
    GreetingEntry(code = "ta", name = "Tamil", nativeLabel = "தமிழ்", template = "வணக்கம், %s"),
    GreetingEntry(code = "fa", name = "Persian", nativeLabel = "فارسی", template = "سلام، %s"),
    GreetingEntry(code = "ur", name = "Urdu", nativeLabel = "اردو", template = "السلام علیکم، %s"),
    GreetingEntry(code = "fil", name = "Filipino", nativeLabel = "Filipino", template = "Kumusta, %s"),
    GreetingEntry(code = "ca", name = "Catalan", nativeLabel = "Català", template = "Hola, %s"),
    GreetingEntry(code = "eu", name = "Basque", nativeLabel = "Euskara", template = "Kaixo, %s"),
    GreetingEntry(code = "gl", name = "Galician", nativeLabel = "Galego", template = "Ola, %s"),
    GreetingEntry(code = "is", name = "Icelandic", nativeLabel = "Íslenska", template = "Halló, %s"),
    GreetingEntry(code = "et", name = "Estonian", nativeLabel = "Eesti", template = "Tere, %s"),
    GreetingEntry(code = "lv", name = "Latvian", nativeLabel = "Latviešu", template = "Sveiki, %s"),
    GreetingEntry(code = "lt", name = "Lithuanian", nativeLabel = "Lietuvių", template = "Sveiki, %s"),
    GreetingEntry(code = "sk", name = "Slovak", nativeLabel = "Slovenčina", template = "Ahoj, %s"),
    GreetingEntry(code = "sl", name = "Slovenian", nativeLabel = "Slovenščina", template = "Živjo, %s"),
    GreetingEntry(code = "hr", name = "Croatian", nativeLabel = "Hrvatski", template = "Bok, %s"),
    GreetingEntry(code = "sr", name = "Serbian", nativeLabel = "Српски", template = "Здраво, %s"),
    GreetingEntry(code = "bg", name = "Bulgarian", nativeLabel = "Български", template = "Здравей, %s"),
    GreetingEntry(code = "ka", name = "Georgian", nativeLabel = "ქართული", template = "გამარჯობა, %s"),
    GreetingEntry(code = "hy", name = "Armenian", nativeLabel = "Հայերեն", template = "Բարև, %s"),
    GreetingEntry(code = "am", name = "Amharic", nativeLabel = "አማርኛ", template = "ሰላም, %s"),
    GreetingEntry(code = "mn", name = "Mongolian", nativeLabel = "Монгол", template = "Сайн уу, %s"),
    GreetingEntry(code = "ne", name = "Nepali", nativeLabel = "नेपाली", template = "नमस्कार, %s"),
    GreetingEntry(code = "kk", name = "Kazakh", nativeLabel = "Қазақша", template = "Сәлем, %s"),
    GreetingEntry(code = "uz", name = "Uzbek", nativeLabel = "Oʻzbekcha", template = "Salom, %s"),
    GreetingEntry(code = "yo", name = "Yoruba", nativeLabel = "Yorùbá", template = "Báwo, %s"),
    GreetingEntry(code = "zu", name = "Zulu", nativeLabel = "isiZulu", template = "Sawubona, %s"),
)

private val greetingIndex: Map<String, GreetingEntry> = greetings.associateBy { it.code }

fun lookupGreeting(code: String): GreetingEntry = greetingIndex[code.trim()] ?: greetingIndex.getValue("en")
