pub(crate) struct Greeting {
    pub(crate) lang_code: &'static str,
    pub(crate) lang_english: &'static str,
    pub(crate) lang_native: &'static str,
    pub(crate) template: &'static str,
    pub(crate) default_name: &'static str,
}

pub(crate) const GREETINGS: &[Greeting] = &[
    Greeting {
        lang_code: "en",
        lang_english: "English",
        lang_native: "English",
        template: "Hello %s",
        default_name: "Mary",
    },
    Greeting {
        lang_code: "fr",
        lang_english: "French",
        lang_native: "Français",
        template: "Bonjour %s",
        default_name: "Marie",
    },
    Greeting {
        lang_code: "es",
        lang_english: "Spanish",
        lang_native: "Español",
        template: "Hola %s",
        default_name: "María",
    },
    Greeting {
        lang_code: "de",
        lang_english: "German",
        lang_native: "Deutsch",
        template: "Hallo %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "it",
        lang_english: "Italian",
        lang_native: "Italiano",
        template: "Ciao %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "pt",
        lang_english: "Portuguese",
        lang_native: "Português",
        template: "Olá %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "nl",
        lang_english: "Dutch",
        lang_native: "Nederlands",
        template: "Hallo %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "ru",
        lang_english: "Russian",
        lang_native: "Русский",
        template: "Привет %s",
        default_name: "Мария",
    },
    Greeting {
        lang_code: "ja",
        lang_english: "Japanese",
        lang_native: "日本語",
        template: "こんにちは、%sさん",
        default_name: "マリア",
    },
    Greeting {
        lang_code: "zh",
        lang_english: "Chinese",
        lang_native: "中文",
        template: "你好，%s",
        default_name: "玛丽",
    },
    Greeting {
        lang_code: "ko",
        lang_english: "Korean",
        lang_native: "한국어",
        template: "안녕하세요 %s",
        default_name: "마리아",
    },
    Greeting {
        lang_code: "ar",
        lang_english: "Arabic",
        lang_native: "العربية",
        template: "مرحبا، %s",
        default_name: "ماريا",
    },
    Greeting {
        lang_code: "hi",
        lang_english: "Hindi",
        lang_native: "हिन्दी",
        template: "नमस्ते %s",
        default_name: "मारिया",
    },
    Greeting {
        lang_code: "tr",
        lang_english: "Turkish",
        lang_native: "Türkçe",
        template: "Merhaba %s",
        default_name: "Meryem",
    },
    Greeting {
        lang_code: "pl",
        lang_english: "Polish",
        lang_native: "Polski",
        template: "Cześć %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "sv",
        lang_english: "Swedish",
        lang_native: "Svenska",
        template: "Hej %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "no",
        lang_english: "Norwegian",
        lang_native: "Norsk",
        template: "Hei %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "da",
        lang_english: "Danish",
        lang_native: "Dansk",
        template: "Hej %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "fi",
        lang_english: "Finnish",
        lang_native: "Suomi",
        template: "Hei %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "cs",
        lang_english: "Czech",
        lang_native: "Čeština",
        template: "Ahoj %s",
        default_name: "Marie",
    },
    Greeting {
        lang_code: "ro",
        lang_english: "Romanian",
        lang_native: "Română",
        template: "Bună %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "hu",
        lang_english: "Hungarian",
        lang_native: "Magyar",
        template: "Szia %s",
        default_name: "Mária",
    },
    Greeting {
        lang_code: "el",
        lang_english: "Greek",
        lang_native: "Ελληνικά",
        template: "Γεια σου %s",
        default_name: "Μαρία",
    },
    Greeting {
        lang_code: "th",
        lang_english: "Thai",
        lang_native: "ไทย",
        template: "สวัสดี %s",
        default_name: "มาเรีย",
    },
    Greeting {
        lang_code: "vi",
        lang_english: "Vietnamese",
        lang_native: "Tiếng Việt",
        template: "Xin chào %s",
        default_name: "Mary",
    },
    Greeting {
        lang_code: "id",
        lang_english: "Indonesian",
        lang_native: "Bahasa Indonesia",
        template: "Halo %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "ms",
        lang_english: "Malay",
        lang_native: "Bahasa Melayu",
        template: "Hai %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "sw",
        lang_english: "Swahili",
        lang_native: "Kiswahili",
        template: "Habari %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "he",
        lang_english: "Hebrew",
        lang_native: "עברית",
        template: "שלום %s",
        default_name: "מרים",
    },
    Greeting {
        lang_code: "uk",
        lang_english: "Ukrainian",
        lang_native: "Українська",
        template: "Привіт %s",
        default_name: "Марія",
    },
    Greeting {
        lang_code: "bn",
        lang_english: "Bengali",
        lang_native: "বাংলা",
        template: "নমস্কার %s",
        default_name: "মারিয়া",
    },
    Greeting {
        lang_code: "ta",
        lang_english: "Tamil",
        lang_native: "தமிழ்",
        template: "வணக்கம் %s",
        default_name: "மரியா",
    },
    Greeting {
        lang_code: "fa",
        lang_english: "Persian",
        lang_native: "فارسی",
        template: "سلام، %s",
        default_name: "ماریا",
    },
    Greeting {
        lang_code: "ur",
        lang_english: "Urdu",
        lang_native: "اردو",
        template: "السلام علیکم، %s",
        default_name: "ماریہ",
    },
    Greeting {
        lang_code: "fil",
        lang_english: "Filipino",
        lang_native: "Filipino",
        template: "Kumusta %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "ca",
        lang_english: "Catalan",
        lang_native: "Català",
        template: "Hola %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "eu",
        lang_english: "Basque",
        lang_native: "Euskara",
        template: "Kaixo %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "gl",
        lang_english: "Galician",
        lang_native: "Galego",
        template: "Ola %s",
        default_name: "María",
    },
    Greeting {
        lang_code: "is",
        lang_english: "Icelandic",
        lang_native: "Íslenska",
        template: "Halló %s",
        default_name: "María",
    },
    Greeting {
        lang_code: "et",
        lang_english: "Estonian",
        lang_native: "Eesti",
        template: "Tere %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "lv",
        lang_english: "Latvian",
        lang_native: "Latviešu",
        template: "Sveiki %s",
        default_name: "Marija",
    },
    Greeting {
        lang_code: "lt",
        lang_english: "Lithuanian",
        lang_native: "Lietuvių",
        template: "Sveiki %s",
        default_name: "Marija",
    },
    Greeting {
        lang_code: "sk",
        lang_english: "Slovak",
        lang_native: "Slovenčina",
        template: "Ahoj %s",
        default_name: "Mária",
    },
    Greeting {
        lang_code: "sl",
        lang_english: "Slovenian",
        lang_native: "Slovenščina",
        template: "Živjo %s",
        default_name: "Marija",
    },
    Greeting {
        lang_code: "hr",
        lang_english: "Croatian",
        lang_native: "Hrvatski",
        template: "Bok %s",
        default_name: "Marija",
    },
    Greeting {
        lang_code: "sr",
        lang_english: "Serbian",
        lang_native: "Српски",
        template: "Здраво %s",
        default_name: "Марија",
    },
    Greeting {
        lang_code: "bg",
        lang_english: "Bulgarian",
        lang_native: "Български",
        template: "Здравей %s",
        default_name: "Мария",
    },
    Greeting {
        lang_code: "ka",
        lang_english: "Georgian",
        lang_native: "ქართული",
        template: "გამარჯობა %s",
        default_name: "მარიამ",
    },
    Greeting {
        lang_code: "hy",
        lang_english: "Armenian",
        lang_native: "Հայերեն",
        template: "Բարև %s",
        default_name: "Մարիա",
    },
    Greeting {
        lang_code: "am",
        lang_english: "Amharic",
        lang_native: "አማርኛ",
        template: "ሰላም %s",
        default_name: "ማሪያ",
    },
    Greeting {
        lang_code: "mn",
        lang_english: "Mongolian",
        lang_native: "Монгол",
        template: "Сайн уу %s",
        default_name: "Мария",
    },
    Greeting {
        lang_code: "ne",
        lang_english: "Nepali",
        lang_native: "नेपाली",
        template: "नमस्कार %s",
        default_name: "मारिया",
    },
    Greeting {
        lang_code: "kk",
        lang_english: "Kazakh",
        lang_native: "Қазақша",
        template: "Сәлем %s",
        default_name: "Мария",
    },
    Greeting {
        lang_code: "uz",
        lang_english: "Uzbek",
        lang_native: "Oʻzbekcha",
        template: "Salom %s",
        default_name: "Mariya",
    },
    Greeting {
        lang_code: "yo",
        lang_english: "Yoruba",
        lang_native: "Yorùbá",
        template: "Báwo %s",
        default_name: "Maria",
    },
    Greeting {
        lang_code: "zu",
        lang_english: "Zulu",
        lang_native: "isiZulu",
        template: "Sawubona %s",
        default_name: "uMaria",
    },
];

pub(crate) fn lookup(code: &str) -> &'static Greeting {
    GREETINGS
        .iter()
        .find(|greeting| greeting.lang_code == code)
        .unwrap_or(&GREETINGS[0])
}
