package org.organicprogramming.gabriel.greeting.kotlinholon.internal

data class GreetingData(
    val langCode: String,
    val langEnglish: String,
    val langNative: String,
    val template: String,
    val defaultName: String,
)

val GREETINGS = listOf(
    GreetingData("en", "English", "English", "Hello %s", "Mary"),
    GreetingData("fr", "French", "Français", "Bonjour %s", "Marie"),
    GreetingData("es", "Spanish", "Español", "Hola %s", "María"),
    GreetingData("de", "German", "Deutsch", "Hallo %s", "Maria"),
    GreetingData("it", "Italian", "Italiano", "Ciao %s", "Maria"),
    GreetingData("pt", "Portuguese", "Português", "Olá %s", "Maria"),
    GreetingData("nl", "Dutch", "Nederlands", "Hallo %s", "Maria"),
    GreetingData("ru", "Russian", "Русский", "Привет %s", "Мария"),
    GreetingData("ja", "Japanese", "日本語", "こんにちは、%sさん", "マリア"),
    GreetingData("zh", "Chinese", "中文", "你好，%s", "玛丽"),
    GreetingData("ko", "Korean", "한국어", "안녕하세요 %s", "마리아"),
    GreetingData("ar", "Arabic", "العربية", "مرحبا، %s", "ماريا"),
    GreetingData("hi", "Hindi", "हिन्दी", "नमस्ते %s", "मारिया"),
    GreetingData("tr", "Turkish", "Türkçe", "Merhaba %s", "Meryem"),
    GreetingData("pl", "Polish", "Polski", "Cześć %s", "Maria"),
    GreetingData("sv", "Swedish", "Svenska", "Hej %s", "Maria"),
    GreetingData("no", "Norwegian", "Norsk", "Hei %s", "Maria"),
    GreetingData("da", "Danish", "Dansk", "Hej %s", "Maria"),
    GreetingData("fi", "Finnish", "Suomi", "Hei %s", "Maria"),
    GreetingData("cs", "Czech", "Čeština", "Ahoj %s", "Marie"),
    GreetingData("ro", "Romanian", "Română", "Bună %s", "Maria"),
    GreetingData("hu", "Hungarian", "Magyar", "Szia %s", "Mária"),
    GreetingData("el", "Greek", "Ελληνικά", "Γεια σου %s", "Μαρία"),
    GreetingData("th", "Thai", "ไทย", "สวัสดี %s", "มาเรีย"),
    GreetingData("vi", "Vietnamese", "Tiếng Việt", "Xin chào %s", "Mary"),
    GreetingData("id", "Indonesian", "Bahasa Indonesia", "Halo %s", "Maria"),
    GreetingData("ms", "Malay", "Bahasa Melayu", "Hai %s", "Maria"),
    GreetingData("sw", "Swahili", "Kiswahili", "Habari %s", "Maria"),
    GreetingData("he", "Hebrew", "עברית", "שלום %s", "מרים"),
    GreetingData("uk", "Ukrainian", "Українська", "Привіт %s", "Марія"),
    GreetingData("bn", "Bengali", "বাংলা", "নমস্কার %s", "মারিয়া"),
    GreetingData("ta", "Tamil", "தமிழ்", "வணக்கம் %s", "மரியா"),
    GreetingData("fa", "Persian", "فارسی", "سلام، %s", "ماریا"),
    GreetingData("ur", "Urdu", "اردو", "السلام علیکم، %s", "ماریہ"),
    GreetingData("fil", "Filipino", "Filipino", "Kumusta %s", "Maria"),
    GreetingData("ca", "Catalan", "Català", "Hola %s", "Maria"),
    GreetingData("eu", "Basque", "Euskara", "Kaixo %s", "Maria"),
    GreetingData("gl", "Galician", "Galego", "Ola %s", "María"),
    GreetingData("is", "Icelandic", "Íslenska", "Halló %s", "María"),
    GreetingData("et", "Estonian", "Eesti", "Tere %s", "Maria"),
    GreetingData("lv", "Latvian", "Latviešu", "Sveiki %s", "Marija"),
    GreetingData("lt", "Lithuanian", "Lietuvių", "Sveiki %s", "Marija"),
    GreetingData("sk", "Slovak", "Slovenčina", "Ahoj %s", "Mária"),
    GreetingData("sl", "Slovenian", "Slovenščina", "Živjo %s", "Marija"),
    GreetingData("hr", "Croatian", "Hrvatski", "Bok %s", "Marija"),
    GreetingData("sr", "Serbian", "Српски", "Здраво %s", "Марија"),
    GreetingData("bg", "Bulgarian", "Български", "Здравей %s", "Мария"),
    GreetingData("ka", "Georgian", "ქართული", "გამარჯობა %s", "მარიამ"),
    GreetingData("hy", "Armenian", "Հայերեն", "Բարև %s", "Մարիա"),
    GreetingData("am", "Amharic", "አማርኛ", "ሰላም %s", "ማሪያ"),
    GreetingData("mn", "Mongolian", "Монгол", "Сайн уу %s", "Мария"),
    GreetingData("ne", "Nepali", "नेपाली", "नमस्कार %s", "मारिया"),
    GreetingData("kk", "Kazakh", "Қазақша", "Сәлем %s", "Мария"),
    GreetingData("uz", "Uzbek", "Oʻzbekcha", "Salom %s", "Mariya"),
    GreetingData("yo", "Yoruba", "Yorùbá", "Báwo %s", "Maria"),
    GreetingData("zu", "Zulu", "isiZulu", "Sawubona %s", "uMaria"),
)

val GREETING_BY_CODE = GREETINGS.associateBy { it.langCode }
