name: gudule_daemon_greeting_dart
description: Greeting daemon recipe for Organic Programming.
version: 0.4.2
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  grpc: ^5.1.0
  holons:
    path: ../../../sdk/dart-holons
  protobuf: ^6.0.0
  test: ^1.25.0
