pub struct Greeting {
    pub code: &'static str,
    pub name: &'static str,
    pub native: &'static str,
    pub template: &'static str,
}

pub const GREETINGS: &[Greeting] = &[
    Greeting { code: "en", name: "English", native: "English", template: "Hello, %s" },
    Greeting { code: "fr", name: "French", native: "Français", template: "Bonjour, %s" },
    Greeting { code: "es", name: "Spanish", native: "Español", template: "Hola, %s" },
    Greeting { code: "de", name: "German", native: "Deutsch", template: "Hallo, %s" },
    Greeting { code: "it", name: "Italian", native: "Italiano", template: "Ciao, %s" },
    Greeting { code: "pt", name: "Portuguese", native: "Português", template: "Olá, %s" },
    Greeting { code: "nl", name: "Dutch", native: "Nederlands", template: "Hallo, %s" },
    Greeting { code: "ru", name: "Russian", native: "Русский", template: "Привет, %s" },
    Greeting { code: "ja", name: "Japanese", native: "日本語", template: "こんにちは、%sさん" },
    Greeting { code: "zh", name: "Chinese", native: "中文", template: "你好，%s" },
    Greeting { code: "ko", name: "Korean", native: "한국어", template: "안녕하세요, %s" },
    Greeting { code: "ar", name: "Arabic", native: "العربية", template: "مرحبا، %s" },
    Greeting { code: "hi", name: "Hindi", native: "हिन्दी", template: "नमस्ते, %s" },
    Greeting { code: "tr", name: "Turkish", native: "Türkçe", template: "Merhaba, %s" },
    Greeting { code: "pl", name: "Polish", native: "Polski", template: "Cześć, %s" },
    Greeting { code: "sv", name: "Swedish", native: "Svenska", template: "Hej, %s" },
    Greeting { code: "no", name: "Norwegian", native: "Norsk", template: "Hei, %s" },
    Greeting { code: "da", name: "Danish", native: "Dansk", template: "Hej, %s" },
    Greeting { code: "fi", name: "Finnish", native: "Suomi", template: "Hei, %s" },
    Greeting { code: "cs", name: "Czech", native: "Čeština", template: "Ahoj, %s" },
    Greeting { code: "ro", name: "Romanian", native: "Română", template: "Bună, %s" },
    Greeting { code: "hu", name: "Hungarian", native: "Magyar", template: "Szia, %s" },
    Greeting { code: "el", name: "Greek", native: "Ελληνικά", template: "Γεια σου, %s" },
    Greeting { code: "th", name: "Thai", native: "ไทย", template: "สวัสดี, %s" },
    Greeting { code: "vi", name: "Vietnamese", native: "Tiếng Việt", template: "Xin chào, %s" },
    Greeting { code: "id", name: "Indonesian", native: "Bahasa Indonesia", template: "Halo, %s" },
    Greeting { code: "ms", name: "Malay", native: "Bahasa Melayu", template: "Hai, %s" },
    Greeting { code: "sw", name: "Swahili", native: "Kiswahili", template: "Habari, %s" },
    Greeting { code: "he", name: "Hebrew", native: "עברית", template: "שלום, %s" },
    Greeting { code: "uk", name: "Ukrainian", native: "Українська", template: "Привіт, %s" },
    Greeting { code: "bn", name: "Bengali", native: "বাংলা", template: "নমস্কার, %s" },
    Greeting { code: "ta", name: "Tamil", native: "தமிழ்", template: "வணக்கம், %s" },
    Greeting { code: "fa", name: "Persian", native: "فارسی", template: "سلام، %s" },
    Greeting { code: "ur", name: "Urdu", native: "اردو", template: "السلام علیکم، %s" },
    Greeting { code: "fil", name: "Filipino", native: "Filipino", template: "Kumusta, %s" },
    Greeting { code: "ca", name: "Catalan", native: "Català", template: "Hola, %s" },
    Greeting { code: "eu", name: "Basque", native: "Euskara", template: "Kaixo, %s" },
    Greeting { code: "gl", name: "Galician", native: "Galego", template: "Ola, %s" },
    Greeting { code: "is", name: "Icelandic", native: "Íslenska", template: "Halló, %s" },
    Greeting { code: "et", name: "Estonian", native: "Eesti", template: "Tere, %s" },
    Greeting { code: "lv", name: "Latvian", native: "Latviešu", template: "Sveiki, %s" },
    Greeting { code: "lt", name: "Lithuanian", native: "Lietuvių", template: "Sveiki, %s" },
    Greeting { code: "sk", name: "Slovak", native: "Slovenčina", template: "Ahoj, %s" },
    Greeting { code: "sl", name: "Slovenian", native: "Slovenščina", template: "Živjo, %s" },
    Greeting { code: "hr", name: "Croatian", native: "Hrvatski", template: "Bok, %s" },
    Greeting { code: "sr", name: "Serbian", native: "Српски", template: "Здраво, %s" },
    Greeting { code: "bg", name: "Bulgarian", native: "Български", template: "Здравей, %s" },
    Greeting { code: "ka", name: "Georgian", native: "ქართული", template: "გამარჯობა, %s" },
    Greeting { code: "hy", name: "Armenian", native: "Հայերեն", template: "Բարև, %s" },
    Greeting { code: "am", name: "Amharic", native: "አማርኛ", template: "ሰላም, %s" },
    Greeting { code: "mn", name: "Mongolian", native: "Монгол", template: "Сайн уу, %s" },
    Greeting { code: "ne", name: "Nepali", native: "नेपाली", template: "नमस्कार, %s" },
    Greeting { code: "kk", name: "Kazakh", native: "Қазақша", template: "Сәлем, %s" },
    Greeting { code: "uz", name: "Uzbek", native: "Oʻzbekcha", template: "Salom, %s" },
    Greeting { code: "yo", name: "Yoruba", native: "Yorùbá", template: "Báwo, %s" },
    Greeting { code: "zu", name: "Zulu", native: "isiZulu", template: "Sawubona, %s" },
];

pub fn lookup(code: &str) -> &'static Greeting {
    GREETINGS
        .iter()
        .find(|greeting| greeting.code == code)
        .unwrap_or(&GREETINGS[0])
}
