//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: holons/v1/observability.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// HolonObservability emits OTLP-shaped records through the SDK-managed
/// observability service. Events are LogRecord values with event_name set.
///
/// Canonical event_name values for this wave:
///   instance.spawned
///   instance.ready
///   instance.exited
///   instance.crashed
///   session.started
///   session.ended
///   handler.panic
///   config.reloaded
///
/// Usage: instantiate `Holons_V1_HolonObservabilityClient`, then call methods of this protocol to make API calls.
public protocol Holons_V1_HolonObservabilityClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol? { get }

  func logs(
    _ request: Holons_V1_LogsRequest,
    callOptions: CallOptions?,
    handler: @escaping (Holons_V1_LogRecord) -> Void
  ) -> ServerStreamingCall<Holons_V1_LogsRequest, Holons_V1_LogRecord>

  func metrics(
    _ request: Holons_V1_MetricsRequest,
    callOptions: CallOptions?,
    handler: @escaping (Holons_V1_Metric) -> Void
  ) -> ServerStreamingCall<Holons_V1_MetricsRequest, Holons_V1_Metric>

  func events(
    _ request: Holons_V1_EventsRequest,
    callOptions: CallOptions?,
    handler: @escaping (Holons_V1_LogRecord) -> Void
  ) -> ServerStreamingCall<Holons_V1_EventsRequest, Holons_V1_LogRecord>
}

extension Holons_V1_HolonObservabilityClientProtocol {
  public var serviceName: String {
    return "holons.v1.HolonObservability"
  }

  /// Server streaming call to Logs
  ///
  /// - Parameters:
  ///   - request: Request to send to Logs.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func logs(
    _ request: Holons_V1_LogsRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Holons_V1_LogRecord) -> Void
  ) -> ServerStreamingCall<Holons_V1_LogsRequest, Holons_V1_LogRecord> {
    return self.makeServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.logs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLogsInterceptors() ?? [],
      handler: handler
    )
  }

  /// Server streaming call to Metrics
  ///
  /// - Parameters:
  ///   - request: Request to send to Metrics.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func metrics(
    _ request: Holons_V1_MetricsRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Holons_V1_Metric) -> Void
  ) -> ServerStreamingCall<Holons_V1_MetricsRequest, Holons_V1_Metric> {
    return self.makeServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.metrics.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMetricsInterceptors() ?? [],
      handler: handler
    )
  }

  /// Server streaming call to Events
  ///
  /// - Parameters:
  ///   - request: Request to send to Events.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func events(
    _ request: Holons_V1_EventsRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Holons_V1_LogRecord) -> Void
  ) -> ServerStreamingCall<Holons_V1_EventsRequest, Holons_V1_LogRecord> {
    return self.makeServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.events.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEventsInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Holons_V1_HolonObservabilityClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Holons_V1_HolonObservabilityNIOClient")
public final class Holons_V1_HolonObservabilityClient: Holons_V1_HolonObservabilityClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the holons.v1.HolonObservability service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct Holons_V1_HolonObservabilityNIOClient: Holons_V1_HolonObservabilityClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol?

  /// Creates a client for the holons.v1.HolonObservability service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// HolonObservability emits OTLP-shaped records through the SDK-managed
/// observability service. Events are LogRecord values with event_name set.
///
/// Canonical event_name values for this wave:
///   instance.spawned
///   instance.ready
///   instance.exited
///   instance.crashed
///   session.started
///   session.ended
///   handler.panic
///   config.reloaded
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Holons_V1_HolonObservabilityAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol? { get }

  func makeLogsCall(
    _ request: Holons_V1_LogsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Holons_V1_LogsRequest, Holons_V1_LogRecord>

  func makeMetricsCall(
    _ request: Holons_V1_MetricsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Holons_V1_MetricsRequest, Holons_V1_Metric>

  func makeEventsCall(
    _ request: Holons_V1_EventsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Holons_V1_EventsRequest, Holons_V1_LogRecord>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Holons_V1_HolonObservabilityAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Holons_V1_HolonObservabilityClientMetadata.serviceDescriptor
  }

  public var interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeLogsCall(
    _ request: Holons_V1_LogsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Holons_V1_LogsRequest, Holons_V1_LogRecord> {
    return self.makeAsyncServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.logs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLogsInterceptors() ?? []
    )
  }

  public func makeMetricsCall(
    _ request: Holons_V1_MetricsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Holons_V1_MetricsRequest, Holons_V1_Metric> {
    return self.makeAsyncServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.metrics.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMetricsInterceptors() ?? []
    )
  }

  public func makeEventsCall(
    _ request: Holons_V1_EventsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Holons_V1_EventsRequest, Holons_V1_LogRecord> {
    return self.makeAsyncServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.events.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEventsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Holons_V1_HolonObservabilityAsyncClientProtocol {
  public func logs(
    _ request: Holons_V1_LogsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Holons_V1_LogRecord> {
    return self.performAsyncServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.logs.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLogsInterceptors() ?? []
    )
  }

  public func metrics(
    _ request: Holons_V1_MetricsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Holons_V1_Metric> {
    return self.performAsyncServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.metrics.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMetricsInterceptors() ?? []
    )
  }

  public func events(
    _ request: Holons_V1_EventsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Holons_V1_LogRecord> {
    return self.performAsyncServerStreamingCall(
      path: Holons_V1_HolonObservabilityClientMetadata.Methods.events.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEventsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct Holons_V1_HolonObservabilityAsyncClient: Holons_V1_HolonObservabilityAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol Holons_V1_HolonObservabilityClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'logs'.
  func makeLogsInterceptors() -> [ClientInterceptor<Holons_V1_LogsRequest, Holons_V1_LogRecord>]

  /// - Returns: Interceptors to use when invoking 'metrics'.
  func makeMetricsInterceptors() -> [ClientInterceptor<Holons_V1_MetricsRequest, Holons_V1_Metric>]

  /// - Returns: Interceptors to use when invoking 'events'.
  func makeEventsInterceptors() -> [ClientInterceptor<Holons_V1_EventsRequest, Holons_V1_LogRecord>]
}

public enum Holons_V1_HolonObservabilityClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HolonObservability",
    fullName: "holons.v1.HolonObservability",
    methods: [
      Holons_V1_HolonObservabilityClientMetadata.Methods.logs,
      Holons_V1_HolonObservabilityClientMetadata.Methods.metrics,
      Holons_V1_HolonObservabilityClientMetadata.Methods.events,
    ]
  )

  public enum Methods {
    public static let logs = GRPCMethodDescriptor(
      name: "Logs",
      path: "/holons.v1.HolonObservability/Logs",
      type: GRPCCallType.serverStreaming
    )

    public static let metrics = GRPCMethodDescriptor(
      name: "Metrics",
      path: "/holons.v1.HolonObservability/Metrics",
      type: GRPCCallType.serverStreaming
    )

    public static let events = GRPCMethodDescriptor(
      name: "Events",
      path: "/holons.v1.HolonObservability/Events",
      type: GRPCCallType.serverStreaming
    )
  }
}

/// HolonObservability emits OTLP-shaped records through the SDK-managed
/// observability service. Events are LogRecord values with event_name set.
///
/// Canonical event_name values for this wave:
///   instance.spawned
///   instance.ready
///   instance.exited
///   instance.crashed
///   session.started
///   session.ended
///   handler.panic
///   config.reloaded
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Holons_V1_HolonObservabilityProvider: CallHandlerProvider {
  var interceptors: Holons_V1_HolonObservabilityServerInterceptorFactoryProtocol? { get }

  func logs(request: Holons_V1_LogsRequest, context: StreamingResponseCallContext<Holons_V1_LogRecord>) -> EventLoopFuture<GRPCStatus>

  func metrics(request: Holons_V1_MetricsRequest, context: StreamingResponseCallContext<Holons_V1_Metric>) -> EventLoopFuture<GRPCStatus>

  func events(request: Holons_V1_EventsRequest, context: StreamingResponseCallContext<Holons_V1_LogRecord>) -> EventLoopFuture<GRPCStatus>
}

extension Holons_V1_HolonObservabilityProvider {
  public var serviceName: Substring {
    return Holons_V1_HolonObservabilityServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Logs":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Holons_V1_LogsRequest>(),
        responseSerializer: ProtobufSerializer<Holons_V1_LogRecord>(),
        interceptors: self.interceptors?.makeLogsInterceptors() ?? [],
        userFunction: self.logs(request:context:)
      )

    case "Metrics":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Holons_V1_MetricsRequest>(),
        responseSerializer: ProtobufSerializer<Holons_V1_Metric>(),
        interceptors: self.interceptors?.makeMetricsInterceptors() ?? [],
        userFunction: self.metrics(request:context:)
      )

    case "Events":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Holons_V1_EventsRequest>(),
        responseSerializer: ProtobufSerializer<Holons_V1_LogRecord>(),
        interceptors: self.interceptors?.makeEventsInterceptors() ?? [],
        userFunction: self.events(request:context:)
      )

    default:
      return nil
    }
  }
}

/// HolonObservability emits OTLP-shaped records through the SDK-managed
/// observability service. Events are LogRecord values with event_name set.
///
/// Canonical event_name values for this wave:
///   instance.spawned
///   instance.ready
///   instance.exited
///   instance.crashed
///   session.started
///   session.ended
///   handler.panic
///   config.reloaded
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol Holons_V1_HolonObservabilityAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Holons_V1_HolonObservabilityServerInterceptorFactoryProtocol? { get }

  func logs(
    request: Holons_V1_LogsRequest,
    responseStream: GRPCAsyncResponseStreamWriter<Holons_V1_LogRecord>,
    context: GRPCAsyncServerCallContext
  ) async throws

  func metrics(
    request: Holons_V1_MetricsRequest,
    responseStream: GRPCAsyncResponseStreamWriter<Holons_V1_Metric>,
    context: GRPCAsyncServerCallContext
  ) async throws

  func events(
    request: Holons_V1_EventsRequest,
    responseStream: GRPCAsyncResponseStreamWriter<Holons_V1_LogRecord>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Holons_V1_HolonObservabilityAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return Holons_V1_HolonObservabilityServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return Holons_V1_HolonObservabilityServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: Holons_V1_HolonObservabilityServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Logs":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Holons_V1_LogsRequest>(),
        responseSerializer: ProtobufSerializer<Holons_V1_LogRecord>(),
        interceptors: self.interceptors?.makeLogsInterceptors() ?? [],
        wrapping: { try await self.logs(request: $0, responseStream: $1, context: $2) }
      )

    case "Metrics":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Holons_V1_MetricsRequest>(),
        responseSerializer: ProtobufSerializer<Holons_V1_Metric>(),
        interceptors: self.interceptors?.makeMetricsInterceptors() ?? [],
        wrapping: { try await self.metrics(request: $0, responseStream: $1, context: $2) }
      )

    case "Events":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Holons_V1_EventsRequest>(),
        responseSerializer: ProtobufSerializer<Holons_V1_LogRecord>(),
        interceptors: self.interceptors?.makeEventsInterceptors() ?? [],
        wrapping: { try await self.events(request: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol Holons_V1_HolonObservabilityServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'logs'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLogsInterceptors() -> [ServerInterceptor<Holons_V1_LogsRequest, Holons_V1_LogRecord>]

  /// - Returns: Interceptors to use when handling 'metrics'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeMetricsInterceptors() -> [ServerInterceptor<Holons_V1_MetricsRequest, Holons_V1_Metric>]

  /// - Returns: Interceptors to use when handling 'events'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEventsInterceptors() -> [ServerInterceptor<Holons_V1_EventsRequest, Holons_V1_LogRecord>]
}

public enum Holons_V1_HolonObservabilityServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HolonObservability",
    fullName: "holons.v1.HolonObservability",
    methods: [
      Holons_V1_HolonObservabilityServerMetadata.Methods.logs,
      Holons_V1_HolonObservabilityServerMetadata.Methods.metrics,
      Holons_V1_HolonObservabilityServerMetadata.Methods.events,
    ]
  )

  public enum Methods {
    public static let logs = GRPCMethodDescriptor(
      name: "Logs",
      path: "/holons.v1.HolonObservability/Logs",
      type: GRPCCallType.serverStreaming
    )

    public static let metrics = GRPCMethodDescriptor(
      name: "Metrics",
      path: "/holons.v1.HolonObservability/Metrics",
      type: GRPCCallType.serverStreaming
    )

    public static let events = GRPCMethodDescriptor(
      name: "Events",
      path: "/holons.v1.HolonObservability/Events",
      type: GRPCCallType.serverStreaming
    )
  }
}
