package lifecycle

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/organic-programming/codex-orchestrator/internal/codex"
	"github.com/organic-programming/codex-orchestrator/internal/git"
	"github.com/organic-programming/codex-orchestrator/internal/state"
	"github.com/organic-programming/codex-orchestrator/internal/tasks"
)

func CompleteTask(task tasks.Entry, result codex.Result, setDir string, gitOps *git.Ops) error {
	tasksFile := filepath.Join(setDir, "_TASKS.md")
	taskStatus := taskStatusForOutcome(result.Outcome)

	statusBlock := buildStatusBlock(result)
	if err := writeStatusBlock(task.FilePath, statusBlock); err != nil {
		return err
	}

	var files []string
	files = append(files, task.FilePath, tasksFile)
	if result.Outcome == state.OutcomeFailed {
		reportPath := failureReportPath(task.FilePath)
		if err := os.WriteFile(reportPath, []byte(buildFailureReport(result)), 0o644); err != nil {
			return err
		}
		files = append(files, reportPath)
	} else {
		_ = os.Remove(failureReportPath(task.FilePath))
	}

	if err := updateTaskStatus(tasksFile, task, taskStatus); err != nil {
		return err
	}
	return gitOps.AddCommitPush(fmt.Sprintf("chore: complete %s", taskLabel(task)), files...)
}

func buildStatusBlock(result codex.Result) string {
	var lines []string
	lines = append(lines, "## Status")
	lines = append(lines, "")
	lines = append(lines, fmt.Sprintf("- Outcome: %s", result.Outcome))
	lines = append(lines, fmt.Sprintf("- Attempts: %d", result.Attempts))
	if strings.TrimSpace(result.Output) != "" {
		lines = append(lines, "- Result file: generated by codex")
	}
	if result.Outcome == state.OutcomeFailed {
		lines = append(lines, "- Failure report: see adjacent `.failure.md` file")
	}
	if result.Outcome == state.OutcomeDeferred {
		lines = append(lines, "- Deferred: run again after quota or capacity issues clear")
	}
	return strings.Join(lines, "\n") + "\n"
}

func buildFailureReport(result codex.Result) string {
	var lines []string
	lines = append(lines, "## Failure Report", "")
	for index, attempt := range result.History {
		lines = append(lines, fmt.Sprintf("### Attempt %d (%s)", index+1, attempt.Phase))
		if len(attempt.Verification) > 0 {
			for _, verification := range attempt.Verification {
				status := "PASS"
				if !verification.Passed {
					status = "FAIL"
				}
				lines = append(lines, fmt.Sprintf("- Verification: `%s` → %s", verification.Command, status))
				if strings.TrimSpace(verification.Output) != "" {
					lines = append(lines, fmt.Sprintf("- Output: %s", strings.TrimSpace(verification.Output)))
				}
			}
		}
		if strings.TrimSpace(attempt.Error) != "" {
			lines = append(lines, fmt.Sprintf("- Error: %s", strings.TrimSpace(attempt.Error)))
		}
		if strings.TrimSpace(attempt.Output) != "" {
			lines = append(lines, fmt.Sprintf("- Output: %s", strings.TrimSpace(attempt.Output)))
		}
		lines = append(lines, "")
	}
	if strings.TrimSpace(result.Error) != "" {
		lines = append(lines, "### Conclusion", result.Error)
	}
	return strings.Join(lines, "\n") + "\n"
}
