// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: holons/v1/manifest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// HolonManifest is the single source of truth for a holon's identity,
/// contract, skills, documentation, and operational metadata.
/// Any .proto file can carry this manifest via:
///   option (holons.v1.manifest) = { ... };
///
/// See HOLON_PROTO.md for the full authoring specification.
/// See HOLON_PACKAGE.md for how the package is produced from this manifest.
struct Holons_V1_HolonManifest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var identity: Holons_V1_HolonManifest.Identity {
    get {_storage._identity ?? Holons_V1_HolonManifest.Identity()}
    set {_uniqueStorage()._identity = newValue}
  }
  /// Returns true if `identity` has been explicitly set.
  var hasIdentity: Bool {_storage._identity != nil}
  /// Clears the value of `identity`. Subsequent reads from it will return its default value.
  mutating func clearIdentity() {_uniqueStorage()._identity = nil}

  /// what this holon does, plain language
  var description_p: String {
    get {_storage._description_p}
    set {_uniqueStorage()._description_p = newValue}
  }

  /// primary implementation language (go, swift, dart, rust…)
  var lang: String {
    get {_storage._lang}
    set {_uniqueStorage()._lang = newValue}
  }

  var skills: [Holons_V1_HolonManifest.Skill] {
    get {_storage._skills}
    set {_uniqueStorage()._skills = newValue}
  }

  var contract: Holons_V1_HolonManifest.Contract {
    get {_storage._contract ?? Holons_V1_HolonManifest.Contract()}
    set {_uniqueStorage()._contract = newValue}
  }
  /// Returns true if `contract` has been explicitly set.
  var hasContract: Bool {_storage._contract != nil}
  /// Clears the value of `contract`. Subsequent reads from it will return its default value.
  mutating func clearContract() {_uniqueStorage()._contract = nil}

  /// native | wrapper | composite
  var kind: String {
    get {_storage._kind}
    set {_uniqueStorage()._kind = newValue}
  }

  /// supported platforms
  var platforms: [String] {
    get {_storage._platforms}
    set {_uniqueStorage()._platforms = newValue}
  }

  /// default transport hint (stdio, tcp)
  var transport: String {
    get {_storage._transport}
    set {_uniqueStorage()._transport = newValue}
  }

  var build: Holons_V1_HolonManifest.Build {
    get {_storage._build ?? Holons_V1_HolonManifest.Build()}
    set {_uniqueStorage()._build = newValue}
  }
  /// Returns true if `build` has been explicitly set.
  var hasBuild: Bool {_storage._build != nil}
  /// Clears the value of `build`. Subsequent reads from it will return its default value.
  mutating func clearBuild() {_uniqueStorage()._build = nil}

  var requires: Holons_V1_HolonManifest.Requires {
    get {_storage._requires ?? Holons_V1_HolonManifest.Requires()}
    set {_uniqueStorage()._requires = newValue}
  }
  /// Returns true if `requires` has been explicitly set.
  var hasRequires: Bool {_storage._requires != nil}
  /// Clears the value of `requires`. Subsequent reads from it will return its default value.
  mutating func clearRequires() {_uniqueStorage()._requires = nil}

  var artifacts: Holons_V1_HolonManifest.Artifacts {
    get {_storage._artifacts ?? Holons_V1_HolonManifest.Artifacts()}
    set {_uniqueStorage()._artifacts = newValue}
  }
  /// Returns true if `artifacts` has been explicitly set.
  var hasArtifacts: Bool {_storage._artifacts != nil}
  /// Clears the value of `artifacts`. Subsequent reads from it will return its default value.
  mutating func clearArtifacts() {_uniqueStorage()._artifacts = nil}

  var sequences: [Holons_V1_HolonManifest.Sequence] {
    get {_storage._sequences}
    set {_uniqueStorage()._sequences = newValue}
  }

  /// user-facing documentation in markdown (rendered by `op man`)
  var guide: String {
    get {_storage._guide}
    set {_uniqueStorage()._guide = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct Identity: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// always "holon/v1"
    var schema: String = String()

    /// UUID v4, generated once, never changes
    var uuid: String = String()

    /// the character — what distinguishes this holon (e.g. "Gabriel")
    var givenName: String = String()

    /// the function — what it does (e.g. "Greeting-Go")
    var familyName: String = String()

    /// the dessein in one sentence
    var motto: String = String()

    /// who designed this holon (human or agent)
    var composer: String = String()

    /// draft | stable | deprecated | dead
    var status: String = String()

    /// ISO 8601 date of creation (YYYY-MM-DD)
    var born: String = String()

    /// semver, e.g. "0.4.1" — no "v" prefix
    var version: String = String()

    /// short names for slug resolution (e.g. "op", "rgo")
    var aliases: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Skill: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// kebab-case identifier
    var name: String = String()

    /// what this skill achieves
    var description_p: String = String()

    /// trigger condition (when to invoke)
    var when: String = String()

    /// ordered human-readable steps
    var steps: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Sequence: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// kebab-case identifier
    var name: String = String()

    /// what this sequence achieves
    var description_p: String = String()

    /// input parameters
    var params: [Holons_V1_HolonManifest.Sequence.Param] = []

    /// ordered shell commands (Go text/template syntax)
    var steps: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct Param: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var name: String = String()

      var description_p: String = String()

      var required: Bool = false

      /// default value if not provided
      var `default`: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    init() {}
  }

  struct Contract: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// e.g. "api/v1/holon.proto"
    var proto: String = String()

    /// fully qualified service name
    var service: String = String()

    /// exposed RPC method names
    var rpcs: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Build: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Compiled:    go-module | cargo | cmake | swift-package
    /// Interpreted: python | node | ruby
    /// Transpiled:  typescript (source is TS, dist is JS)
    /// Mobile:      dart | flutter
    /// Composite:   recipe (multi-step orchestration)
    /// None:        none (no build step, pre-built or external)
    var runner: String = String()

    /// entry point (go-module: "./cmd")
    var main: String = String()

    /// Recipe-mode fields (runner == "recipe")
    var defaults: Holons_V1_HolonManifest.Build.Defaults {
      get {_defaults ?? Holons_V1_HolonManifest.Build.Defaults()}
      set {_defaults = newValue}
    }
    /// Returns true if `defaults` has been explicitly set.
    var hasDefaults: Bool {self._defaults != nil}
    /// Clears the value of `defaults`. Subsequent reads from it will return its default value.
    mutating func clearDefaults() {self._defaults = nil}

    var members: [Holons_V1_HolonManifest.Build.Member] = []

    var targets: Dictionary<String,Holons_V1_HolonManifest.Build.Target> = [:]

    /// Source files containing Go template expressions (e.g. {{ .Version }}).
    /// Resolved with identity data before the language build, restored after.
    var templates: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct Defaults: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// e.g. "macos", "linux"
      var target: String = String()

      /// e.g. "debug", "release"
      var mode: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct Member: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// e.g. "daemon", "app"
      var id: String = String()

      /// relative path to the member
      var path: String = String()

      /// holon | component
      var type: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct Target: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var steps: [Holons_V1_HolonManifest.Step] = []

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    init() {}

    fileprivate var _defaults: Holons_V1_HolonManifest.Build.Defaults? = nil
  }

  struct Step: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var action: Holons_V1_HolonManifest.Step.OneOf_Action? = nil

    var exec: Holons_V1_HolonManifest.Step.Exec {
      get {
        if case .exec(let v)? = action {return v}
        return Holons_V1_HolonManifest.Step.Exec()
      }
      set {action = .exec(newValue)}
    }

    var copy: Holons_V1_HolonManifest.Step.Copy {
      get {
        if case .copy(let v)? = action {return v}
        return Holons_V1_HolonManifest.Step.Copy()
      }
      set {action = .copy(newValue)}
    }

    /// member id to build
    var buildMember: String {
      get {
        if case .buildMember(let v)? = action {return v}
        return String()
      }
      set {action = .buildMember(newValue)}
    }

    var assertFile: Holons_V1_HolonManifest.Step.AssertFile {
      get {
        if case .assertFile(let v)? = action {return v}
        return Holons_V1_HolonManifest.Step.AssertFile()
      }
      set {action = .assertFile(newValue)}
    }

    var copyArtifact: Holons_V1_HolonManifest.Step.CopyArtifact {
      get {
        if case .copyArtifact(let v)? = action {return v}
        return Holons_V1_HolonManifest.Step.CopyArtifact()
      }
      set {action = .copyArtifact(newValue)}
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_Action: Equatable, Sendable {
      case exec(Holons_V1_HolonManifest.Step.Exec)
      case copy(Holons_V1_HolonManifest.Step.Copy)
      /// member id to build
      case buildMember(String)
      case assertFile(Holons_V1_HolonManifest.Step.AssertFile)
      case copyArtifact(Holons_V1_HolonManifest.Step.CopyArtifact)

    }

    struct Exec: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var cwd: String = String()

      var argv: [String] = []

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct Copy: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var from: String = String()

      var to: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct AssertFile: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var path: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    struct CopyArtifact: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var from: String = String()

      var to: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    init() {}
  }

  struct Requires: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// CLI tools required in PATH
    var commands: [String] = []

    /// source files that must exist
    var files: [String] = []

    /// supported targets (macos, linux, windows…)
    var platforms: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Artifacts: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// for native/wrapper holons
    var binary: String = String()

    /// for composites (e.g. ".app" path)
    var primary: String = String()

    /// per-platform overrides
    var byTarget: Dictionary<String,Holons_V1_HolonManifest.Artifacts.TargetArtifacts> = [:]

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct TargetArtifacts: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var debug: String = String()

      var release: String = String()

      var profile: String = String()

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}
    }

    init() {}
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Extension support defined in manifest.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_FileOptions {

  var Holons_V1_manifest: Holons_V1_HolonManifest {
    get {return getExtensionValue(ext: Holons_V1_Extensions_manifest) ?? Holons_V1_HolonManifest()}
    set {setExtensionValue(ext: Holons_V1_Extensions_manifest, value: newValue)}
  }
  /// Returns true if extension `Holons_V1_Extensions_manifest`
  /// has been explicitly set.
  var hasHolons_V1_manifest: Bool {
    return hasExtensionValue(ext: Holons_V1_Extensions_manifest)
  }
  /// Clears the value of extension `Holons_V1_Extensions_manifest`.
  /// Subsequent reads from it will return its default value.
  mutating func clearHolons_V1_manifest() {
    clearExtensionValue(ext: Holons_V1_Extensions_manifest)
  }

}

// MARK: - File's ExtensionMap: Holons_V1_Manifest_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
let Holons_V1_Manifest_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Holons_V1_Extensions_manifest
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

let Holons_V1_Extensions_manifest = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Holons_V1_HolonManifest>, SwiftProtobuf.Google_Protobuf_FileOptions>(
  _protobuf_fieldNumber: 50000,
  fieldName: "holons.v1.manifest"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "holons.v1"

extension Holons_V1_HolonManifest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HolonManifest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}identity\0\u{2}\u{2}description\0\u{1}lang\0\u{1}skills\0\u{1}contract\0\u{1}kind\0\u{1}platforms\0\u{1}transport\0\u{1}build\0\u{1}requires\0\u{2}\u{2}artifacts\0\u{1}sequences\0\u{1}guide\0\u{c}\u{2}\u{1}\u{c}\u{c}\u{1}")

  fileprivate class _StorageClass {
    var _identity: Holons_V1_HolonManifest.Identity? = nil
    var _description_p: String = String()
    var _lang: String = String()
    var _skills: [Holons_V1_HolonManifest.Skill] = []
    var _contract: Holons_V1_HolonManifest.Contract? = nil
    var _kind: String = String()
    var _platforms: [String] = []
    var _transport: String = String()
    var _build: Holons_V1_HolonManifest.Build? = nil
    var _requires: Holons_V1_HolonManifest.Requires? = nil
    var _artifacts: Holons_V1_HolonManifest.Artifacts? = nil
    var _sequences: [Holons_V1_HolonManifest.Sequence] = []
    var _guide: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _identity = source._identity
      _description_p = source._description_p
      _lang = source._lang
      _skills = source._skills
      _contract = source._contract
      _kind = source._kind
      _platforms = source._platforms
      _transport = source._transport
      _build = source._build
      _requires = source._requires
      _artifacts = source._artifacts
      _sequences = source._sequences
      _guide = source._guide
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._identity) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._lang) }()
        case 5: try { try decoder.decodeRepeatedMessageField(value: &_storage._skills) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._contract) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._kind) }()
        case 8: try { try decoder.decodeRepeatedStringField(value: &_storage._platforms) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._transport) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._build) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._requires) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._artifacts) }()
        case 14: try { try decoder.decodeRepeatedMessageField(value: &_storage._sequences) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._guide) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._identity {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._description_p.isEmpty {
        try visitor.visitSingularStringField(value: _storage._description_p, fieldNumber: 3)
      }
      if !_storage._lang.isEmpty {
        try visitor.visitSingularStringField(value: _storage._lang, fieldNumber: 4)
      }
      if !_storage._skills.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._skills, fieldNumber: 5)
      }
      try { if let v = _storage._contract {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if !_storage._kind.isEmpty {
        try visitor.visitSingularStringField(value: _storage._kind, fieldNumber: 7)
      }
      if !_storage._platforms.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._platforms, fieldNumber: 8)
      }
      if !_storage._transport.isEmpty {
        try visitor.visitSingularStringField(value: _storage._transport, fieldNumber: 9)
      }
      try { if let v = _storage._build {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._requires {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._artifacts {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      if !_storage._sequences.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._sequences, fieldNumber: 14)
      }
      if !_storage._guide.isEmpty {
        try visitor.visitSingularStringField(value: _storage._guide, fieldNumber: 15)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest, rhs: Holons_V1_HolonManifest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._identity != rhs_storage._identity {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._lang != rhs_storage._lang {return false}
        if _storage._skills != rhs_storage._skills {return false}
        if _storage._contract != rhs_storage._contract {return false}
        if _storage._kind != rhs_storage._kind {return false}
        if _storage._platforms != rhs_storage._platforms {return false}
        if _storage._transport != rhs_storage._transport {return false}
        if _storage._build != rhs_storage._build {return false}
        if _storage._requires != rhs_storage._requires {return false}
        if _storage._artifacts != rhs_storage._artifacts {return false}
        if _storage._sequences != rhs_storage._sequences {return false}
        if _storage._guide != rhs_storage._guide {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Identity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.protoMessageName + ".Identity"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}schema\0\u{1}uuid\0\u{3}given_name\0\u{3}family_name\0\u{1}motto\0\u{1}composer\0\u{2}\u{2}status\0\u{1}born\0\u{1}version\0\u{1}aliases\0\u{c}\u{7}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.schema) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.uuid) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.givenName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.familyName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.motto) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.composer) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.born) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 11: try { try decoder.decodeRepeatedStringField(value: &self.aliases) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.schema.isEmpty {
      try visitor.visitSingularStringField(value: self.schema, fieldNumber: 1)
    }
    if !self.uuid.isEmpty {
      try visitor.visitSingularStringField(value: self.uuid, fieldNumber: 2)
    }
    if !self.givenName.isEmpty {
      try visitor.visitSingularStringField(value: self.givenName, fieldNumber: 3)
    }
    if !self.familyName.isEmpty {
      try visitor.visitSingularStringField(value: self.familyName, fieldNumber: 4)
    }
    if !self.motto.isEmpty {
      try visitor.visitSingularStringField(value: self.motto, fieldNumber: 5)
    }
    if !self.composer.isEmpty {
      try visitor.visitSingularStringField(value: self.composer, fieldNumber: 6)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 8)
    }
    if !self.born.isEmpty {
      try visitor.visitSingularStringField(value: self.born, fieldNumber: 9)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 10)
    }
    if !self.aliases.isEmpty {
      try visitor.visitRepeatedStringField(value: self.aliases, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Identity, rhs: Holons_V1_HolonManifest.Identity) -> Bool {
    if lhs.schema != rhs.schema {return false}
    if lhs.uuid != rhs.uuid {return false}
    if lhs.givenName != rhs.givenName {return false}
    if lhs.familyName != rhs.familyName {return false}
    if lhs.motto != rhs.motto {return false}
    if lhs.composer != rhs.composer {return false}
    if lhs.status != rhs.status {return false}
    if lhs.born != rhs.born {return false}
    if lhs.version != rhs.version {return false}
    if lhs.aliases != rhs.aliases {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Skill: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.protoMessageName + ".Skill"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{1}when\0\u{1}steps\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.when) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.steps) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if !self.when.isEmpty {
      try visitor.visitSingularStringField(value: self.when, fieldNumber: 3)
    }
    if !self.steps.isEmpty {
      try visitor.visitRepeatedStringField(value: self.steps, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Skill, rhs: Holons_V1_HolonManifest.Skill) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.when != rhs.when {return false}
    if lhs.steps != rhs.steps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Sequence: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.protoMessageName + ".Sequence"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{1}params\0\u{1}steps\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.params) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.steps) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if !self.params.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.params, fieldNumber: 3)
    }
    if !self.steps.isEmpty {
      try visitor.visitRepeatedStringField(value: self.steps, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Sequence, rhs: Holons_V1_HolonManifest.Sequence) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.params != rhs.params {return false}
    if lhs.steps != rhs.steps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Sequence.Param: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Sequence.protoMessageName + ".Param"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{1}required\0\u{1}default\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.required) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.`default`) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if self.required != false {
      try visitor.visitSingularBoolField(value: self.required, fieldNumber: 3)
    }
    if !self.`default`.isEmpty {
      try visitor.visitSingularStringField(value: self.`default`, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Sequence.Param, rhs: Holons_V1_HolonManifest.Sequence.Param) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.required != rhs.required {return false}
    if lhs.`default` != rhs.`default` {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Contract: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.protoMessageName + ".Contract"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}proto\0\u{1}service\0\u{1}rpcs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.proto) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.service) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.rpcs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.proto.isEmpty {
      try visitor.visitSingularStringField(value: self.proto, fieldNumber: 1)
    }
    if !self.service.isEmpty {
      try visitor.visitSingularStringField(value: self.service, fieldNumber: 2)
    }
    if !self.rpcs.isEmpty {
      try visitor.visitRepeatedStringField(value: self.rpcs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Contract, rhs: Holons_V1_HolonManifest.Contract) -> Bool {
    if lhs.proto != rhs.proto {return false}
    if lhs.service != rhs.service {return false}
    if lhs.rpcs != rhs.rpcs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Build: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.protoMessageName + ".Build"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}runner\0\u{1}main\0\u{1}defaults\0\u{1}members\0\u{1}targets\0\u{1}templates\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.runner) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.main) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._defaults) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.members) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Holons_V1_HolonManifest.Build.Target>.self, value: &self.targets) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.templates) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.runner.isEmpty {
      try visitor.visitSingularStringField(value: self.runner, fieldNumber: 1)
    }
    if !self.main.isEmpty {
      try visitor.visitSingularStringField(value: self.main, fieldNumber: 2)
    }
    try { if let v = self._defaults {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.members.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.members, fieldNumber: 4)
    }
    if !self.targets.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Holons_V1_HolonManifest.Build.Target>.self, value: self.targets, fieldNumber: 5)
    }
    if !self.templates.isEmpty {
      try visitor.visitRepeatedStringField(value: self.templates, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Build, rhs: Holons_V1_HolonManifest.Build) -> Bool {
    if lhs.runner != rhs.runner {return false}
    if lhs.main != rhs.main {return false}
    if lhs._defaults != rhs._defaults {return false}
    if lhs.members != rhs.members {return false}
    if lhs.targets != rhs.targets {return false}
    if lhs.templates != rhs.templates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Build.Defaults: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Build.protoMessageName + ".Defaults"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}target\0\u{1}mode\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.target) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.mode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.target.isEmpty {
      try visitor.visitSingularStringField(value: self.target, fieldNumber: 1)
    }
    if !self.mode.isEmpty {
      try visitor.visitSingularStringField(value: self.mode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Build.Defaults, rhs: Holons_V1_HolonManifest.Build.Defaults) -> Bool {
    if lhs.target != rhs.target {return false}
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Build.Member: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Build.protoMessageName + ".Member"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}path\0\u{1}type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.type) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 2)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Build.Member, rhs: Holons_V1_HolonManifest.Build.Member) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.path != rhs.path {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Build.Target: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Build.protoMessageName + ".Target"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}steps\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.steps) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.steps.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.steps, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Build.Target, rhs: Holons_V1_HolonManifest.Build.Target) -> Bool {
    if lhs.steps != rhs.steps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Step: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.protoMessageName + ".Step"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}exec\0\u{1}copy\0\u{3}build_member\0\u{3}assert_file\0\u{3}copy_artifact\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Holons_V1_HolonManifest.Step.Exec?
        var hadOneofValue = false
        if let current = self.action {
          hadOneofValue = true
          if case .exec(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.action = .exec(v)
        }
      }()
      case 2: try {
        var v: Holons_V1_HolonManifest.Step.Copy?
        var hadOneofValue = false
        if let current = self.action {
          hadOneofValue = true
          if case .copy(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.action = .copy(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.action != nil {try decoder.handleConflictingOneOf()}
          self.action = .buildMember(v)
        }
      }()
      case 4: try {
        var v: Holons_V1_HolonManifest.Step.AssertFile?
        var hadOneofValue = false
        if let current = self.action {
          hadOneofValue = true
          if case .assertFile(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.action = .assertFile(v)
        }
      }()
      case 5: try {
        var v: Holons_V1_HolonManifest.Step.CopyArtifact?
        var hadOneofValue = false
        if let current = self.action {
          hadOneofValue = true
          if case .copyArtifact(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.action = .copyArtifact(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.action {
    case .exec?: try {
      guard case .exec(let v)? = self.action else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .copy?: try {
      guard case .copy(let v)? = self.action else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .buildMember?: try {
      guard case .buildMember(let v)? = self.action else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case .assertFile?: try {
      guard case .assertFile(let v)? = self.action else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .copyArtifact?: try {
      guard case .copyArtifact(let v)? = self.action else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Step, rhs: Holons_V1_HolonManifest.Step) -> Bool {
    if lhs.action != rhs.action {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Step.Exec: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Step.protoMessageName + ".Exec"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}cwd\0\u{1}argv\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.cwd) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.argv) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.cwd.isEmpty {
      try visitor.visitSingularStringField(value: self.cwd, fieldNumber: 1)
    }
    if !self.argv.isEmpty {
      try visitor.visitRepeatedStringField(value: self.argv, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Step.Exec, rhs: Holons_V1_HolonManifest.Step.Exec) -> Bool {
    if lhs.cwd != rhs.cwd {return false}
    if lhs.argv != rhs.argv {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Step.Copy: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Step.protoMessageName + ".Copy"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}from\0\u{1}to\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.from) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.to) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.from.isEmpty {
      try visitor.visitSingularStringField(value: self.from, fieldNumber: 1)
    }
    if !self.to.isEmpty {
      try visitor.visitSingularStringField(value: self.to, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Step.Copy, rhs: Holons_V1_HolonManifest.Step.Copy) -> Bool {
    if lhs.from != rhs.from {return false}
    if lhs.to != rhs.to {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Step.AssertFile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Step.protoMessageName + ".AssertFile"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Step.AssertFile, rhs: Holons_V1_HolonManifest.Step.AssertFile) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Step.CopyArtifact: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Step.protoMessageName + ".CopyArtifact"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}from\0\u{1}to\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.from) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.to) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.from.isEmpty {
      try visitor.visitSingularStringField(value: self.from, fieldNumber: 1)
    }
    if !self.to.isEmpty {
      try visitor.visitSingularStringField(value: self.to, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Step.CopyArtifact, rhs: Holons_V1_HolonManifest.Step.CopyArtifact) -> Bool {
    if lhs.from != rhs.from {return false}
    if lhs.to != rhs.to {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Requires: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.protoMessageName + ".Requires"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}commands\0\u{1}files\0\u{1}platforms\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.commands) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.files) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.platforms) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.commands.isEmpty {
      try visitor.visitRepeatedStringField(value: self.commands, fieldNumber: 1)
    }
    if !self.files.isEmpty {
      try visitor.visitRepeatedStringField(value: self.files, fieldNumber: 2)
    }
    if !self.platforms.isEmpty {
      try visitor.visitRepeatedStringField(value: self.platforms, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Requires, rhs: Holons_V1_HolonManifest.Requires) -> Bool {
    if lhs.commands != rhs.commands {return false}
    if lhs.files != rhs.files {return false}
    if lhs.platforms != rhs.platforms {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Artifacts: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.protoMessageName + ".Artifacts"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}binary\0\u{1}primary\0\u{3}by_target\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.binary) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.primary) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Holons_V1_HolonManifest.Artifacts.TargetArtifacts>.self, value: &self.byTarget) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.binary.isEmpty {
      try visitor.visitSingularStringField(value: self.binary, fieldNumber: 1)
    }
    if !self.primary.isEmpty {
      try visitor.visitSingularStringField(value: self.primary, fieldNumber: 2)
    }
    if !self.byTarget.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Holons_V1_HolonManifest.Artifacts.TargetArtifacts>.self, value: self.byTarget, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Artifacts, rhs: Holons_V1_HolonManifest.Artifacts) -> Bool {
    if lhs.binary != rhs.binary {return false}
    if lhs.primary != rhs.primary {return false}
    if lhs.byTarget != rhs.byTarget {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Holons_V1_HolonManifest.Artifacts.TargetArtifacts: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Holons_V1_HolonManifest.Artifacts.protoMessageName + ".TargetArtifacts"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}debug\0\u{1}release\0\u{1}profile\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.debug) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.release) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.profile) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.debug.isEmpty {
      try visitor.visitSingularStringField(value: self.debug, fieldNumber: 1)
    }
    if !self.release.isEmpty {
      try visitor.visitSingularStringField(value: self.release, fieldNumber: 2)
    }
    if !self.profile.isEmpty {
      try visitor.visitSingularStringField(value: self.profile, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Holons_V1_HolonManifest.Artifacts.TargetArtifacts, rhs: Holons_V1_HolonManifest.Artifacts.TargetArtifacts) -> Bool {
    if lhs.debug != rhs.debug {return false}
    if lhs.release != rhs.release {return false}
    if lhs.profile != rhs.profile {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
