// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: echo/v1/echo.proto

package echov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoMode int32

const (
	EchoMode_ECHO_MODE_UNSPECIFIED EchoMode = 0
	EchoMode_ECHO_MODE_UPPER       EchoMode = 1
	EchoMode_ECHO_MODE_LOWER       EchoMode = 2
)

// Enum value maps for EchoMode.
var (
	EchoMode_name = map[int32]string{
		0: "ECHO_MODE_UNSPECIFIED",
		1: "ECHO_MODE_UPPER",
		2: "ECHO_MODE_LOWER",
	}
	EchoMode_value = map[string]int32{
		"ECHO_MODE_UNSPECIFIED": 0,
		"ECHO_MODE_UPPER":       1,
		"ECHO_MODE_LOWER":       2,
	}
)

func (x EchoMode) Enum() *EchoMode {
	p := new(EchoMode)
	*p = x
	return p
}

func (x EchoMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EchoMode) Descriptor() protoreflect.EnumDescriptor {
	return file_echo_v1_echo_proto_enumTypes[0].Descriptor()
}

func (EchoMode) Type() protoreflect.EnumType {
	return &file_echo_v1_echo_proto_enumTypes[0]
}

func (x EchoMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EchoMode.Descriptor instead.
func (EchoMode) EnumDescriptor() ([]byte, []int) {
	return file_echo_v1_echo_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message to echo back.
	// @required
	// @example "hello"
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Tags to include in the response count.
	// @example ["one","two"]
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	// Output mode.
	Mode          EchoMode `protobuf:"varint,3,opt,name=mode,proto3,enum=echo.v1.EchoMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_echo_v1_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v1_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_echo_v1_echo_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PingRequest) GetMode() EchoMode {
	if x != nil {
		return x.Mode
	}
	return EchoMode_ECHO_MODE_UNSPECIFIED
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoed text.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Number of tags seen.
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Mode chosen by the caller.
	Mode          EchoMode `protobuf:"varint,3,opt,name=mode,proto3,enum=echo.v1.EchoMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_echo_v1_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v1_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_echo_v1_echo_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PingResponse) GetMode() EchoMode {
	if x != nil {
		return x.Mode
	}
	return EchoMode_ECHO_MODE_UNSPECIFIED
}

var File_echo_v1_echo_proto protoreflect.FileDescriptor

const file_echo_v1_echo_proto_rawDesc = "" +
	"\n" +
	"\x12echo/v1/echo.proto\x12\aecho.v1\"b\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12%\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x11.echo.v1.EchoModeR\x04mode\"e\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12%\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x11.echo.v1.EchoModeR\x04mode*O\n" +
	"\bEchoMode\x12\x19\n" +
	"\x15ECHO_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fECHO_MODE_UPPER\x10\x01\x12\x13\n" +
	"\x0fECHO_MODE_LOWER\x10\x022B\n" +
	"\vEchoService\x123\n" +
	"\x04Ping\x12\x14.echo.v1.PingRequest\x1a\x15.echo.v1.PingResponseBbZ`github.com/organic-programming/grace-op/internal/cli/testsupport/echoholon/protos/echo/v1;echov1b\x06proto3"

var (
	file_echo_v1_echo_proto_rawDescOnce sync.Once
	file_echo_v1_echo_proto_rawDescData []byte
)

func file_echo_v1_echo_proto_rawDescGZIP() []byte {
	file_echo_v1_echo_proto_rawDescOnce.Do(func() {
		file_echo_v1_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_v1_echo_proto_rawDesc), len(file_echo_v1_echo_proto_rawDesc)))
	})
	return file_echo_v1_echo_proto_rawDescData
}

var file_echo_v1_echo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_echo_v1_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_v1_echo_proto_goTypes = []any{
	(EchoMode)(0),        // 0: echo.v1.EchoMode
	(*PingRequest)(nil),  // 1: echo.v1.PingRequest
	(*PingResponse)(nil), // 2: echo.v1.PingResponse
}
var file_echo_v1_echo_proto_depIdxs = []int32{
	0, // 0: echo.v1.PingRequest.mode:type_name -> echo.v1.EchoMode
	0, // 1: echo.v1.PingResponse.mode:type_name -> echo.v1.EchoMode
	1, // 2: echo.v1.EchoService.Ping:input_type -> echo.v1.PingRequest
	2, // 3: echo.v1.EchoService.Ping:output_type -> echo.v1.PingResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_echo_v1_echo_proto_init() }
func file_echo_v1_echo_proto_init() {
	if File_echo_v1_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_v1_echo_proto_rawDesc), len(file_echo_v1_echo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_v1_echo_proto_goTypes,
		DependencyIndexes: file_echo_v1_echo_proto_depIdxs,
		EnumInfos:         file_echo_v1_echo_proto_enumTypes,
		MessageInfos:      file_echo_v1_echo_proto_msgTypes,
	}.Build()
	File_echo_v1_echo_proto = out.File
	file_echo_v1_echo_proto_goTypes = nil
	file_echo_v1_echo_proto_depIdxs = nil
}
