package holons

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jhump/protoreflect/desc"
	"github.com/organic-programming/grace-op/internal/progress"
)

// generateDocumentation produces .op/doc/REFERENCE.md from parsed
// proto descriptors and the holon manifest.
func generateDocumentation(manifest *LoadedManifest, fds []*desc.FileDescriptor, reporter progress.Reporter) error {
	if len(fds) == 0 {
		return nil
	}

	docDir := filepath.Join(manifest.OpRoot(), "doc")
	if err := os.MkdirAll(docDir, 0755); err != nil {
		return fmt.Errorf("doc gen: mkdir: %w", err)
	}

	slug := manifest.BinaryName()
	if slug == "" {
		slug = filepath.Base(manifest.Dir)
	}
	var buf strings.Builder

	buf.WriteString(fmt.Sprintf("# %s — Reference\n\n", slug))
	buf.WriteString("_This file is machine-generated by `op build`. Do not edit._\n\n")

	// Commands
	buf.WriteString("## Commands\n\n")
	buf.WriteString(fmt.Sprintf("```\nop build %s\nop run %s\n```\n\n", slug, slug))

	// RPC Catalog — collect services from all transitive dependencies.
	allFds := collectAllDescriptors(fds)
	for _, fd := range allFds {
		for _, svc := range fd.GetServices() {
			fqn := svc.GetFullyQualifiedName()
			// Skip HolonMeta service — internal infrastructure.
			if strings.HasSuffix(fqn, "HolonMeta") {
				continue
			}

			buf.WriteString(fmt.Sprintf("## %s\n\n", fqn))
			comment := sourceComment(svc)
			if comment != "" {
				buf.WriteString(comment + "\n\n")
			}

			for _, m := range svc.GetMethods() {
				buf.WriteString(fmt.Sprintf("### %s\n\n", m.GetName()))
				mComment := sourceComment(m)
				if mComment != "" {
					buf.WriteString(mComment + "\n\n")
				}

				example := extractExample(m)
				buf.WriteString(fmt.Sprintf("```\nop grpc+stdio://%s %s '%s'\n```\n\n",
					slug, m.GetName(), example))
			}
		}
	}

	refPath := filepath.Join(docDir, "REFERENCE.md")
	if err := os.WriteFile(refPath, []byte(buf.String()), 0644); err != nil {
		return fmt.Errorf("doc gen: write: %w", err)
	}

	reporter.Step(fmt.Sprintf("doc gen: %s", workspaceRelativePath(refPath)))
	return nil
}

// sourceComment returns the leading comment for a descriptor, cleaned up.
func sourceComment(d desc.Descriptor) string {
	info := d.GetSourceInfo()
	if info == nil {
		return ""
	}
	comment := strings.TrimSpace(info.GetLeadingComments())
	// Strip leading "// " style prefixes line by line.
	lines := strings.Split(comment, "\n")
	var cleaned []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Skip annotation lines in the output (they're machine directives).
		if strings.HasPrefix(line, "@") {
			continue
		}
		if line != "" {
			cleaned = append(cleaned, line)
		}
	}
	return strings.Join(cleaned, " ")
}

// extractExample pulls the @example annotation from a method's comment,
// or returns an empty JSON object as a fallback.
func extractExample(m *desc.MethodDescriptor) string {
	info := m.GetSourceInfo()
	if info == nil {
		return "{}"
	}
	comment := info.GetLeadingComments()
	for _, line := range strings.Split(comment, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "@example ") {
			return strings.TrimPrefix(line, "@example ")
		}
	}
	return "{}"
}

// collectAllDescriptors flattens the transitive dependency tree into a
// deduplicated slice, so doc gen can discover services from imported protos.
func collectAllDescriptors(roots []*desc.FileDescriptor) []*desc.FileDescriptor {
	seen := make(map[string]bool)
	var result []*desc.FileDescriptor
	var walk func(fd *desc.FileDescriptor)
	walk = func(fd *desc.FileDescriptor) {
		name := fd.GetName()
		if seen[name] {
			return
		}
		seen[name] = true
		for _, dep := range fd.GetDependencies() {
			walk(dep)
		}
		result = append(result, fd)
	}
	for _, fd := range roots {
		walk(fd)
	}
	return result
}
