package holons

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/organic-programming/grace-op/internal/progress"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const defaultCoaxReferenceTarget = "tcp://127.0.0.1:60000"

// generateDocumentation produces .op/doc/REFERENCE.md from parsed
// proto descriptors and the holon manifest.
func generateDocumentation(manifest *LoadedManifest, fds []protoreflect.FileDescriptor, reporter progress.Reporter) error {
	if len(fds) == 0 {
		return nil
	}

	docDir := filepath.Join(manifest.OpRoot(), "doc")
	if err := os.MkdirAll(docDir, 0755); err != nil {
		return fmt.Errorf("doc gen: mkdir: %w", err)
	}

	slug := manifest.BinaryName()
	if slug == "" {
		slug = filepath.Base(manifest.Dir)
	}
	var buf strings.Builder

	buf.WriteString(fmt.Sprintf("# %s — Reference\n\n", slug))
	buf.WriteString("_This file is machine-generated by `op build`. Do not edit._\n\n")

	// Commands
	buf.WriteString("## Commands\n\n")
	buf.WriteString(fmt.Sprintf("```\nop build %s\nop run %s\n```\n\n", slug, slug))

	// RPC Catalog — collect services from all transitive dependencies.
	allFds := collectAllDescriptors(fds)
	for _, fd := range allFds {
		services := fd.Services()
		for i := 0; i < services.Len(); i++ {
			svc := services.Get(i)
			fqn := string(svc.FullName())
			// Skip HolonMeta service — internal infrastructure.
			if strings.HasSuffix(fqn, "HolonMeta") {
				continue
			}

			buf.WriteString(fmt.Sprintf("## %s\n\n", fqn))
			comment := sourceComment(svc)
			if comment != "" {
				buf.WriteString(comment + "\n\n")
			}
			if isCOAXReferenceService(svc, comment) {
				buf.WriteString("Call this COAX surface over `tcp://127.0.0.1:60000` by default. The app must be running with COAX enabled, and the port can be changed from the interface.\n\n")
			}

			methods := svc.Methods()
			for j := 0; j < methods.Len(); j++ {
				m := methods.Get(j)
				buf.WriteString(fmt.Sprintf("### %s\n\n", m.Name()))
				mComment := sourceComment(m)
				if mComment != "" {
					buf.WriteString(mComment + "\n\n")
				}
				buf.WriteString(fmt.Sprintf("`%s(%s) -> %s`\n\n",
					m.Name(),
					m.Input().FullName(),
					m.Output().FullName()))
				if messageHasBytesFields(m.Input(), map[string]bool{}) {
					buf.WriteString("_Bytes fields use base64 in JSON examples._\n\n")
				}

				example := exampleInputForMethod(m)
				target := referenceInvocationTarget(slug, svc, comment)
				buf.WriteString(fmt.Sprintf("```\nop %s %s '%s'\n```\n\n",
					target, m.Name(), example))
			}
		}
	}

	refPath := filepath.Join(docDir, "REFERENCE.md")
	if err := os.WriteFile(refPath, []byte(buf.String()), 0644); err != nil {
		return fmt.Errorf("doc gen: write: %w", err)
	}

	reporter.Step(fmt.Sprintf("doc gen: %s", workspaceRelativePath(refPath)))
	return nil
}

// sourceComment returns the leading comment for a descriptor, cleaned up.
func sourceComment(d protoreflect.Descriptor) string {
	if d == nil || d.ParentFile() == nil {
		return ""
	}
	location := d.ParentFile().SourceLocations().ByDescriptor(d)
	comment := strings.TrimSpace(location.LeadingComments)
	// Strip leading "// " style prefixes line by line.
	lines := strings.Split(comment, "\n")
	var cleaned []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Skip annotation lines in the output (they're machine directives).
		if strings.HasPrefix(line, "@") {
			continue
		}
		if line != "" {
			cleaned = append(cleaned, line)
		}
	}
	return strings.Join(cleaned, " ")
}

// extractExample pulls the @example annotation from a method's comment,
// or returns an empty JSON object as a fallback.
func extractExample(m protoreflect.MethodDescriptor) string {
	if m == nil || m.ParentFile() == nil {
		return ""
	}
	location := m.ParentFile().SourceLocations().ByDescriptor(m)
	comment := location.LeadingComments
	for _, line := range strings.Split(comment, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "@example ") {
			return strings.TrimPrefix(line, "@example ")
		}
	}
	return ""
}

// collectAllDescriptors flattens the transitive dependency tree into a
// deduplicated slice, so doc gen can discover services from imported protos.
func collectAllDescriptors(roots []protoreflect.FileDescriptor) []protoreflect.FileDescriptor {
	seen := make(map[string]bool)
	var result []protoreflect.FileDescriptor
	var walk func(fd protoreflect.FileDescriptor)
	walk = func(fd protoreflect.FileDescriptor) {
		if fd == nil {
			return
		}
		name := fd.Path()
		if seen[name] {
			return
		}
		seen[name] = true
		imports := fd.Imports()
		for i := 0; i < imports.Len(); i++ {
			walk(imports.Get(i).FileDescriptor)
		}
		result = append(result, fd)
	}
	for _, fd := range roots {
		walk(fd)
	}
	return result
}

func referenceInvocationTarget(slug string, svc protoreflect.ServiceDescriptor, comment string) string {
	if isCOAXReferenceService(svc, comment) {
		return defaultCoaxReferenceTarget
	}
	return "stdio://" + slug
}

func isCOAXReferenceService(svc protoreflect.ServiceDescriptor, comment string) bool {
	if svc == nil {
		return false
	}
	name := strings.ToLower(strings.TrimSpace(string(svc.FullName())))
	if name == "holons.v1.coaxservice" {
		return true
	}
	return strings.Contains(strings.ToLower(comment), "coax")
}

func exampleInputForMethod(m protoreflect.MethodDescriptor) string {
	if m == nil {
		return "{}"
	}
	if example := strings.TrimSpace(extractExample(m)); example != "" {
		return example
	}
	if input := m.Input(); input != nil {
		if example := exampleJSONForMessage(input, map[string]bool{}); example != "" {
			return example
		}
	}
	return "{}"
}

func exampleJSONForMessage(msg protoreflect.MessageDescriptor, seen map[string]bool) string {
	if msg == nil {
		return "{}"
	}
	key := strings.TrimSpace(string(msg.FullName()))
	if key != "" {
		if seen[key] {
			return "{}"
		}
		seen[key] = true
		defer delete(seen, key)
	}

	fields := msg.Fields()
	if fields.Len() == 0 {
		return "{}"
	}

	parts := make([]string, 0, fields.Len())
	for i := 0; i < fields.Len(); i++ {
		field := fields.Get(i)
		value, ok := exampleJSONForField(field, seen)
		if !ok {
			continue
		}
		parts = append(parts, fmt.Sprintf("%q:%s", field.Name(), value))
	}
	if len(parts) == 0 {
		return "{}"
	}
	return "{" + strings.Join(parts, ",") + "}"
}

func exampleJSONForField(field protoreflect.FieldDescriptor, seen map[string]bool) (string, bool) {
	if field == nil {
		return "", false
	}
	if example := strings.TrimSpace(extractFieldExample(field)); example != "" {
		return normalizeExampleJSON(field, example), true
	}
	if field.IsMap() {
		keyJSON := normalizeExampleJSON(field.MapKey(), defaultScalarExample(field.MapKey()))
		valueJSON, ok := exampleJSONForSingularField(field.MapValue(), seen)
		if !ok {
			return "{}", true
		}
		return "{" + keyJSON + ":" + valueJSON + "}", true
	}
	if field.IsList() {
		valueJSON, ok := exampleJSONForSingularField(field, seen)
		if !ok {
			return "[]", true
		}
		return "[" + valueJSON + "]", true
	}
	return exampleJSONForSingularField(field, seen)
}

func exampleJSONForSingularField(field protoreflect.FieldDescriptor, seen map[string]bool) (string, bool) {
	if field == nil {
		return "", false
	}
	switch field.Kind() {
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return exampleJSONForMessage(field.Message(), seen), true
	case protoreflect.EnumKind:
		name := enumExampleName(field)
		encoded, err := json.Marshal(name)
		if err != nil {
			return "", false
		}
		return string(encoded), true
	default:
		return normalizeExampleJSON(field, defaultScalarExample(field)), true
	}
}

func extractFieldExample(field protoreflect.FieldDescriptor) string {
	if field == nil || field.ParentFile() == nil {
		return ""
	}
	location := field.ParentFile().SourceLocations().ByDescriptor(field)
	comment := location.LeadingComments
	for _, line := range strings.Split(comment, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "@example ") {
			return strings.TrimPrefix(line, "@example ")
		}
	}
	return ""
}

func normalizeExampleJSON(field protoreflect.FieldDescriptor, raw string) string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return `""`
	}
	if json.Valid([]byte(trimmed)) {
		return trimmed
	}
	switch field.Kind() {
	case protoreflect.BytesKind:
		encoded, _ := json.Marshal(base64.StdEncoding.EncodeToString([]byte(trimmed)))
		return string(encoded)
	default:
		encoded, _ := json.Marshal(trimmed)
		return string(encoded)
	}
}

func defaultScalarExample(field protoreflect.FieldDescriptor) string {
	if field == nil {
		return ""
	}
	name := strings.ToLower(strings.TrimSpace(string(field.Name())))
	switch field.Kind() {
	case protoreflect.StringKind:
		switch name {
		case "slug", "member_slug":
			return "gabriel-greeting-go"
		case "transport":
			return "tcp"
		case "code", "lang_code":
			return "fr"
		case "name":
			return "Bob"
		case "method":
			return "greeting.v1.GreetingService/SayHello"
		case "display_name":
			return "Gabriel (Go)"
		default:
			if strings.Contains(name, "port") {
				return "60000"
			}
			if strings.HasSuffix(name, "_uri") || strings.HasSuffix(name, "uri") {
				return defaultCoaxReferenceTarget
			}
			return "example"
		}
	case protoreflect.BoolKind:
		return "true"
	case protoreflect.DoubleKind, protoreflect.FloatKind:
		return "1.0"
	case protoreflect.Int64Kind, protoreflect.Uint64Kind, protoreflect.Int32Kind, protoreflect.Fixed64Kind, protoreflect.Fixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Sfixed32Kind, protoreflect.Sfixed64Kind, protoreflect.Sint32Kind, protoreflect.Sint64Kind:
		return "1"
	case protoreflect.BytesKind:
		payload := `{"name":"Bob","lang_code":"fr"}`
		if name != "payload" {
			payload = "example"
		}
		return base64.StdEncoding.EncodeToString([]byte(payload))
	default:
		return "example"
	}
}

func enumExampleName(field protoreflect.FieldDescriptor) string {
	enumDesc := field.Enum()
	if enumDesc == nil || enumDesc.Values().Len() == 0 {
		return ""
	}
	values := enumDesc.Values()
	for i := 0; i < values.Len(); i++ {
		value := values.Get(i)
		if value.Number() != 0 {
			return string(value.Name())
		}
	}
	return string(values.Get(0).Name())
}

func messageHasBytesFields(msg protoreflect.MessageDescriptor, seen map[string]bool) bool {
	if msg == nil {
		return false
	}
	key := strings.TrimSpace(string(msg.FullName()))
	if key != "" {
		if seen[key] {
			return false
		}
		seen[key] = true
		defer delete(seen, key)
	}
	fields := msg.Fields()
	for i := 0; i < fields.Len(); i++ {
		field := fields.Get(i)
		if field.Kind() == protoreflect.BytesKind {
			return true
		}
		if (field.Kind() == protoreflect.MessageKind || field.Kind() == protoreflect.GroupKind) && messageHasBytesFields(field.Message(), seen) {
			return true
		}
	}
	return false
}
