GREETINGS = [
    {"code": 'en', "name": 'English', "native": 'English', "template": 'Hello, %s'},
    {"code": 'fr', "name": 'French', "native": 'Français', "template": 'Bonjour, %s'},
    {"code": 'es', "name": 'Spanish', "native": 'Español', "template": 'Hola, %s'},
    {"code": 'de', "name": 'German', "native": 'Deutsch', "template": 'Hallo, %s'},
    {"code": 'it', "name": 'Italian', "native": 'Italiano', "template": 'Ciao, %s'},
    {"code": 'pt', "name": 'Portuguese', "native": 'Português', "template": 'Olá, %s'},
    {"code": 'nl', "name": 'Dutch', "native": 'Nederlands', "template": 'Hallo, %s'},
    {"code": 'ru', "name": 'Russian', "native": 'Русский', "template": 'Привет, %s'},
    {"code": 'ja', "name": 'Japanese', "native": '日本語', "template": 'こんにちは、%sさん'},
    {"code": 'zh', "name": 'Chinese', "native": '中文', "template": '你好，%s'},
    {"code": 'ko', "name": 'Korean', "native": '한국어', "template": '안녕하세요, %s'},
    {"code": 'ar', "name": 'Arabic', "native": 'العربية', "template": 'مرحبا، %s'},
    {"code": 'hi', "name": 'Hindi', "native": 'हिन्दी', "template": 'नमस्ते, %s'},
    {"code": 'tr', "name": 'Turkish', "native": 'Türkçe', "template": 'Merhaba, %s'},
    {"code": 'pl', "name": 'Polish', "native": 'Polski', "template": 'Cześć, %s'},
    {"code": 'sv', "name": 'Swedish', "native": 'Svenska', "template": 'Hej, %s'},
    {"code": 'no', "name": 'Norwegian', "native": 'Norsk', "template": 'Hei, %s'},
    {"code": 'da', "name": 'Danish', "native": 'Dansk', "template": 'Hej, %s'},
    {"code": 'fi', "name": 'Finnish', "native": 'Suomi', "template": 'Hei, %s'},
    {"code": 'cs', "name": 'Czech', "native": 'Čeština', "template": 'Ahoj, %s'},
    {"code": 'ro', "name": 'Romanian', "native": 'Română', "template": 'Bună, %s'},
    {"code": 'hu', "name": 'Hungarian', "native": 'Magyar', "template": 'Szia, %s'},
    {"code": 'el', "name": 'Greek', "native": 'Ελληνικά', "template": 'Γεια σου, %s'},
    {"code": 'th', "name": 'Thai', "native": 'ไทย', "template": 'สวัสดี, %s'},
    {"code": 'vi', "name": 'Vietnamese', "native": 'Tiếng Việt', "template": 'Xin chào, %s'},
    {"code": 'id', "name": 'Indonesian', "native": 'Bahasa Indonesia', "template": 'Halo, %s'},
    {"code": 'ms', "name": 'Malay', "native": 'Bahasa Melayu', "template": 'Hai, %s'},
    {"code": 'sw', "name": 'Swahili', "native": 'Kiswahili', "template": 'Habari, %s'},
    {"code": 'he', "name": 'Hebrew', "native": 'עברית', "template": 'שלום, %s'},
    {"code": 'uk', "name": 'Ukrainian', "native": 'Українська', "template": 'Привіт, %s'},
    {"code": 'bn', "name": 'Bengali', "native": 'বাংলা', "template": 'নমস্কার, %s'},
    {"code": 'ta', "name": 'Tamil', "native": 'தமிழ்', "template": 'வணக்கம், %s'},
    {"code": 'fa', "name": 'Persian', "native": 'فارسی', "template": 'سلام، %s'},
    {"code": 'ur', "name": 'Urdu', "native": 'اردو', "template": 'السلام علیکم، %s'},
    {"code": 'fil', "name": 'Filipino', "native": 'Filipino', "template": 'Kumusta, %s'},
    {"code": 'ca', "name": 'Catalan', "native": 'Català', "template": 'Hola, %s'},
    {"code": 'eu', "name": 'Basque', "native": 'Euskara', "template": 'Kaixo, %s'},
    {"code": 'gl', "name": 'Galician', "native": 'Galego', "template": 'Ola, %s'},
    {"code": 'is', "name": 'Icelandic', "native": 'Íslenska', "template": 'Halló, %s'},
    {"code": 'et', "name": 'Estonian', "native": 'Eesti', "template": 'Tere, %s'},
    {"code": 'lv', "name": 'Latvian', "native": 'Latviešu', "template": 'Sveiki, %s'},
    {"code": 'lt', "name": 'Lithuanian', "native": 'Lietuvių', "template": 'Sveiki, %s'},
    {"code": 'sk', "name": 'Slovak', "native": 'Slovenčina', "template": 'Ahoj, %s'},
    {"code": 'sl', "name": 'Slovenian', "native": 'Slovenščina', "template": 'Živjo, %s'},
    {"code": 'hr', "name": 'Croatian', "native": 'Hrvatski', "template": 'Bok, %s'},
    {"code": 'sr', "name": 'Serbian', "native": 'Српски', "template": 'Здраво, %s'},
    {"code": 'bg', "name": 'Bulgarian', "native": 'Български', "template": 'Здравей, %s'},
    {"code": 'ka', "name": 'Georgian', "native": 'ქართული', "template": 'გამარჯობა, %s'},
    {"code": 'hy', "name": 'Armenian', "native": 'Հայերեն', "template": 'Բարև, %s'},
    {"code": 'am', "name": 'Amharic', "native": 'አማርኛ', "template": 'ሰላም, %s'},
    {"code": 'mn', "name": 'Mongolian', "native": 'Монгол', "template": 'Сайн уу, %s'},
    {"code": 'ne', "name": 'Nepali', "native": 'नेपाली', "template": 'नमस्कार, %s'},
    {"code": 'kk', "name": 'Kazakh', "native": 'Қазақша', "template": 'Сәлем, %s'},
    {"code": 'uz', "name": 'Uzbek', "native": 'Oʻzbekcha', "template": 'Salom, %s'},
    {"code": 'yo', "name": 'Yoruba', "native": 'Yorùbá', "template": 'Báwo, %s'},
    {"code": 'zu', "name": 'Zulu', "native": 'isiZulu', "template": 'Sawubona, %s'},
]

INDEX = {entry["code"]: entry for entry in GREETINGS}

def lookup(code: str):
    return INDEX.get(code, INDEX["en"])
